@host = http://localhost:3000

### Add a node
POST {{host}}/nodes

### Delete a node
DELETE {{host}}/nodes/5

### Add an edge
POST {{host}}/edges
Content-Type: application/json

{ "source_node_title": 9, "target_node_title": 7 }

### Delete an edge
DELETE {{host}}/edges/1/2

### Does the graph have a cycle?
GET {{host}}/queries/cycles

### All paths between two nodes
GET {{host}}/queries/paths?from=33dfc1b2-f78c-4885-8d5a-fd247a77ed89&to=0fd60289-750b-451c-bf2d-0c7a142df77b

### Connected components
GET {{host}}/queries/components

### Neighbors of a node
GET {{host}}/queries/degrees/0fd60289-750b-451c-bf2d-0c7a142df77b
