/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Edges {
  source_node: string;
  target_node: string;
}

export interface Nodes {
  id: Generated<string>;
  title: Generated<number>;
}

export interface DB {
  edges: Edges;
  nodes: Nodes;
}
